name: Write Config
method: POST
url: $base_url/api/configs/:key
timeout: 0
followRedirects: true
maxRedirects: 5
path_params:
  - name: key
    value: $config_key
body: |-
  {
    "content": "config file content"
  }
body_type: json
